### ISSUE TITLE
ZLS Keeps crashing on some source files

### ISSUE THREAD

**Issue by cinemast** [zigtools/zls#146]
Thanks for providing ZLS!

Opening [this file](https://github.com/nobloat/os/blob/master/kernel/framebuffer.zig) for example keeps crashing ZLS in VSCode for me.

Here is the log:
```
/home/user/zig-linux-x86_64-0.6.0+d1755e7f1/lib/zig/std/debug.zig:223:14: 0x24459b in std.debug.assert (zls)
    if (!ok) unreachable; // assertion failure
             ^
/home/user/zig-linux-x86_64-0.6.0+d1755e7f1/lib/zig/std/hash_map.zig:437:19: 0x339787 in std.hash_map.HashMapUnmanaged([]const u8,*document_store.Handle,std.hash_map.hashString,std.hash_map.eqlString,true).putNoClobber (zls)
            assert(!result.found_existing);
                  ^
/home/user/zig-linux-x86_64-0.6.0+d1755e7f1/lib/zig/std/hash_map.zig:167:47: 0x2c5df3 in std.hash_map.HashMap([]const u8,*document_store.Handle,std.hash_map.hashString,std.hash_map.eqlString,true).putNoClobber (zls)
            return self.unmanaged.putNoClobber(self.allocator, key, value);
                                              ^
/mnt/c/Users/user/git/zls/src/document_store.zig:251:34: 0x2c3cff in document_store.newDocument (zls)
    try self.handles.putNoClobber(uri, handle);
                                 ^
/mnt/c/Users/user/git/zls/src/document_store.zig:240:63: 0x2c3a3c in document_store.newDocument (zls)
                const build_file_handle = try self.newDocument(build_file_uri, build_file_text);
                                                              ^
/mnt/c/Users/user/git/zls/src/document_store.zig:271:32: 0x2a30b8 in document_store.openDocument (zls)
    return try self.newDocument(duped_uri, duped_text);
                               ^
/mnt/c/Users/user/git/zls/src/main.zig:1138:51: 0x28e949 in openDocumentHandler (zls)
    const handle = try document_store.openDocument(req.params.textDocument.uri, req.params.textDocument.text);
                                                  ^
/mnt/c/Users/user/git/zls/src/main.zig:1452:53: 0x27db4c in processJsonRpc (zls)
                    done = extractErr(method_info[2](arena, id, request_obj, config));
                                                    ^
/mnt/c/Users/user/git/zls/src/main.zig:1649:27: 0x272411 in main (zls)
        try processJsonRpc(&arena, &json_parser, buf, config);
                          ^
/home/user/zig-linux-x86_64-0.6.0+d1755e7f1/lib/zig/std/start.zig:252:37: 0x245cdd in std.start.posixCallMainAndExit (zls)
            const result = root.main() catch |err| {
                                    ^
/home/user/zig-linux-x86_64-0.6.0+d1755e7f1/lib/zig/std/start.zig:123:5: 0x245a1f in std.start._start (zls)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
    ^
[Error - 10:43:53 AM] Connection to server got closed. Server will not be restarted.
[Error - 10:43:53 AM] Request textDocument/documentSymbol failed.
Error: Connection got disposed.
	at Object.dispose (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/main.js:967:25)
	at Object.dispose (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:74:35)
	at LanguageClient.handleConnectionClosed (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:2320:42)
	at LanguageClient.handleConnectionClosed (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/main.js:155:15)
	at closeHandler (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-languageclient/lib/client.js:2307:18)
	at CallbackList.invoke (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:125:36)
	at closeHandler (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/main.js:288:26)
	at CallbackList.invoke (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:62:39)
	at Emitter.fire (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/events.js:125:36)
	at StreamMessageReader.fireClose (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/messageReader.js:111:27)
	at Socket.<anonymous> (/home/user/.vscode-server/extensions/augusterame.zls-vscode-1.0.2/node_modules/vscode-jsonrpc/lib/messageReader.js:151:46)
	at Socket.emit (events.js:205:15)
	at Pipe.<anonymous> (net.js:586:12)
```

**Comment by alexnask** [comment]
I'll check this out soon.  
Could you post the directory structure of the project it is crashing in?  
(This is a crash because we try to add a build file that has already been opened which should never happen)  

It would help me a lot to reproduce

**Comment by cinemast** [comment]
It is this project here: https://github.com/nobloat/os/

**Comment by cinemast** [comment]
Here is the missing debug log:

```
[Info  - 3:33:09 PM] [info-main] Found zig in PATH: /home/user/zig-linux-x86_64-0.6.0+d1755e7f1/zig

[Info  - 3:33:09 PM] [info-main] Using zig executable /home/user/zig-linux-x86_64-0.6.0+d1755e7f1/zig

[Info  - 3:33:09 PM] [info-main] Resolved standard library from executable: /home/user/zig-linux-x86_64-0.6.0+d1755e7f1/lib/zig

[debug-main] Got workspace folders in initialization.

[debug-main] Loaded folder file:///mnt/c/Users/user/git/os

[Info  - 3:33:09 PM] [info-main] ClientCapabilities{ .supports_snippets = true, .supports_semantic_tokens = true, .hover_supports_md = true, .completion_doc_supports_md = true, .supports_workspace_folders = true }

[debug-main] Took 1ms to process method initialize

[debug-main] Took 0ms to process method initialized

[debug-doc_store] Opened document: file:///mnt/c/Users/user/git/os/kernel/arch/x86_64/io.zig

[debug-doc_store] Opened document: file:///mnt/c/Users/user/git/os/build.zig

[debug-doc_store] Document is a build file, extracting packages...

[debug-doc_store] Finished zig run for build file file:///mnt/c/Users/user/git/os/build.zig

[debug-main] Took 77ms to process method textDocument/didOpen

[debug-main] Took 1ms to process method textDocument/documentSymbol

[debug-main] Took 1ms to process method textDocument/semanticTokens

[debug-doc_store] Opened document: file:///mnt/c/Users/user/git/os/kernel/psfont.zig

[debug-doc_store] Opened document: file:///mnt/c/Users/user/git/os/build.zig

[debug-doc_store] Document is a build file, extracting packages...

[debug-doc_store] Finished zig run for build file file:///mnt/c/Users/user/git/os/build.zig

reached unreachable code
```

**Comment by cinemast** [comment]
Apparently this is realted to the mounted WSL directory. If VSCode works on a path outside of /mnt/Users/... it works fine.

**Comment by jackwakefield** [comment]
This seems to happen because VS Code [encodes spaces in URIs](https://github.com/microsoft/vscode-uri/blob/master/src/index.ts#L976).

When `newDocument` is called from a request by VS Code below a URI would be `file:///c%3A/Users/Jack%20Wakefield/source/zls/src/analysis.zig`
https://github.com/zigtools/zls/blob/e8c20351d85da8eb4bf22480045b994007284d69/src/document_store.zig#L272

But when it's called within `newDocument` below with a URI returned by `URI.fromPath` this would be `file:///c%3A/Users/Jack Wakefield/source/zls/`
https://github.com/zigtools/zls/blob/e8c20351d85da8eb4bf22480045b994007284d69/src/document_store.zig#L241

Adding space to reserved chars fixed this for me, but I'm not sure if that's the correct fix as it's not technically reserved according to the RFC, from what I can see. I'm happy to send in a pull request if it is though!

```diff
diff --git a/src/uri.zig b/src/uri.zig
index 59ea9d6..ffcbe4a 100644
--- a/src/uri.zig
+++ b/src/uri.zig
@@ -4,6 +4,7 @@ const reserved_chars = &[_]u8{
     '!', '#', '$', '%', '&', '\'',
     '(', ')', '*', '+', ',', ':',
     ';', '=', '?', '@', '[', ']',
+    ' '
 };
 
 /// Returns a URI from a path, caller owns the memory allocated with `allocator`
```
